# -*- coding: utf-8 -*-
"""Language Detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11WpHTSd-5GD_fH_XHfWAfloI_xcl0b-r
"""

# importing the necessary Python libraries 
import pandas as pd     #used for data cleaning and analysis
import numpy as np      # It provides a multidimensional array object.
from sklearn.feature_extraction.text import CountVectorizer # to build & evaluate Naive Bayes Classifier
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB

# Importing and reading the dataset
data = pd.read_csv("/content/Language Detection.csv")
print(data.head())

# Let’s have a look at whether this dataset contains any null values or not
data.isnull().sum()

#listing what are all the languages present in this dataset: 
data["Language"].value_counts()
#This is a very balanced dataset with no missing values.

# splitting the data into training and test sets
x = np.array(data["Text"])
y = np.array(data["Language"])

cv = CountVectorizer()
X = cv.fit_transform(x)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33,random_state=42)

# using the Multinomial Naïve Bayes algorithm to train the language detection model 
model = MultinomialNB()
model.fit(X_train,y_train)
model.score(X_test,y_test)

# Using Model to detect language.
user = input("Enter a Text: ")
data = cv.transform([user]).toarray()
output = model.predict(data)
print(output)